// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQo7mBht0nKMms0gviobG1OGQcAILK0Wg',
    appId: '1:711951373756:web:a01a95ebff3509419087b9',
    messagingSenderId: '711951373756',
    projectId: 'seoul-energy-charcoal',
    authDomain: 'seoul-energy-charcoal.firebaseapp.com',
    storageBucket: 'seoul-energy-charcoal.firebasestorage.app',
    measurementId: 'G-F6PDL68L2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8sslyPpT3GQjdIEUzb3Fxgs-ExucK6Ww',
    appId: '1:711951373756:android:c89195f7271c8e179087b9',
    messagingSenderId: '711951373756',
    projectId: 'seoul-energy-charcoal',
    storageBucket: 'seoul-energy-charcoal.firebasestorage.app',
  );

}